services:
  - type: web
    name: crud_python_frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build/
    routes:
      - src: /*
        dest: index.html
    envVars:
      - key: NODE_ENV
        value: production